name: CI/CD Pipeline for HolaMundoMultilenguaje

on:
  push:
    branches:
      - master  # Verifica si realmente estás usando la rama 'master', o 'main' si es necesario

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # O considera usar @v3 si es necesario
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - name: Install dependencies
        run: composer install
      - name: Run tests
        run: ./vendor/bin/phpunit tests

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # O considera usar @v3 si es necesario
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - name: Install dependencies
        run: composer install
      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
        run: |
          # Verifica el usuario y los permisos
          whoami
          ls -la /home/ubuntu
          
          # Crear directorio .ssh y configurar clave privada
          sudo mkdir -p /home/ubuntu/.ssh
          echo "$SSH_PRIVATE_KEY" | sudo tee /home/ubuntu/.ssh/id_rsa > /dev/null
          sudo chmod 600 /home/ubuntu/.ssh/id_rsa
          
          # Usar SSH para crear el directorio de despliegue en el servidor
          ssh -o StrictHostKeyChecking=no $USERNAME@$HOST "mkdir -p $DEPLOY_PATH"
          
          # Sincronizar los archivos de la aplicación al servidor
          rsync -avz --delete --no-t --exclude 'tests' --exclude '.git' . $USERNAME@$HOST:$DEPLOY_PATH
          
          # Ejecutar Composer install en el servidor
          ssh -o StrictHostKeyChecking=no $USERNAME@$HOST "cd $DEPLOY_PATH && composer install --no-dev --optimize-autoloader"
          
          # Reiniciar Apache si es necesario
          ssh -o StrictHostKeyChecking=no $USERNAME@$HOST "sudo systemctl restart apache2"
